# ---------------------------------------------------------------------------- #
#                         PLOTBUILD CONFIGURATION FILE                         #
# ---------------------------------------------------------------------------- #
#                                                                              #
#   Uncomment the line below and add your list of worlds                       #
#   if you want to turn on full protection. To allow players to build in       #
#   protected worlds, give them plotbuild.trusted permission. Otherwise they   #
#   will be able to build only inside their plots.                             #
# ---------------------------------------------------------------------------- #

# protectedWorlds:
#   - world1
#   - world2

# ---------------------------------------------------------------------------- #
#                                                                              #
#   Uncomment the line below if you want to enable flight for players leaving  #
#   their own plot. Whithout this setting flight of an Adventurer will be      #
#   disabled when he leaves his plot as his game mode is set back to survival  #
# ---------------------------------------------------------------------------- #

# enableFlight: true

# ---------------------------------------------------------------------------- #
#                                                                              #
#   Uncomment the line below if you want to change the time a player has to    #
#   wait until he can claim another plot. Number is cooldown time in seconds.  #
#   Without this setting default is 20 seconds.                                #
# ---------------------------------------------------------------------------- #

# claimCooldown: 20